In [1]:
import numpy as np   # استدعاء مكتبة numpy

A = np.arange(1, 21).reshape(4, 5)
# إنشاء أرقام من 1 إلى 20 ثم تحويلها إلى 4 صفوف و5 أعمدة

print(A)             # طباعة المصفوفة
print(A.dtype)       # نوع البيانات
print(A.ndim)        # عدد الأبعاد
print(A.shape)       # شكل المصفوفة
print(A.size)        # عدد العناصر
print(A.itemsize)    # حجم العنصر بالبايت

B = A.reshape(5, 4)  # تغيير شكل المصفوفة إلى 5x4

print(B)             # طباعة B

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
int64
2
(4, 5)
20
8
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
import numpy as np

a = np.array([[0., 0., 0.],
              [10., 10., 10.],
              [20., 20., 20.],
              [30., 30., 30.]])
# إنشاء المصفوفة a

b = np.array([0., 1., 2.])
# إنشاء المصفوفة b

c = a + b
# جمع b مع كل صف في a باستخدام Broadcasting

print(c)

mask = (c >= 22)
# إنشاء مصفوفة True/False للقيم الأكبر أو تساوي 22

print(mask)

count = np.sum(mask)
# حساب عدد القيم True

print(count)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]
[[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]
4


In [3]:
import numpy as np

grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])
# إنشاء مصفوفة الدرجات

print(np.sum(grades))
# مجموع جميع القيم

print(np.min(grades))
# أصغر قيمة

print(np.max(grades))
# أكبر قيمة

print(np.mean(grades))
# المتوسط

print(np.std(grades))
# الانحراف المعياري

print(np.var(grades))
# التباين

print(np.mean(grades, axis=0))
# متوسط كل عمود

print(np.mean(grades, axis=1))
# متوسط كل صف

print(np.max(grades, axis=1))
# أكبر قيمة بكل صف

1054
70
100
87.83333333333333
8.792357792739987
77.30555555555556
[95.25 85.25 83.  ]
[84.33333333 92.33333333 87.         87.66666667]
[ 96 100  94 100]


In [4]:
import numpy as np

arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])
# إنشاء المصفوفة

print(np.sum(arr, axis=1))
# مجموع كل صف

print(np.sum(arr, axis=0))
# مجموع كل عمود

print(np.mean(arr))
# المتوسط العام للمصفوفة

[12  9 27]
[10 16 22]
5.333333333333333


In [5]:
import numpy as np

A = np.array([[10, 20, 30],
              [40, 50, 60]])
# إنشاء A

B = np.array([1, 2, 3])
# إنشاء B

print(A + B)
# جمع B مع A باستخدام Broadcasting

print(A * 2)
# ضرب جميع العناصر في 2

print(A - 5)
# طرح 5 من جميع العناصر

[[11 22 33]
 [41 52 63]]
[[ 20  40  60]
 [ 80 100 120]]
[[ 5 15 25]
 [35 45 55]]


In [6]:
import numpy as np

grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])
# إنشاء مصفوفة الدرجات

print(np.argmax(grades))
# موقع أكبر عنصر في كامل المصفوفة

print(np.argmax(grades, axis=1))
# موقع أكبر عنصر بكل صف

print(np.argmin(grades, axis=0))
# موقع أصغر عنصر بكل عمود

5
[2 2 1]
[2 1 2]


In [7]:
import numpy as np

def manhattan_distance(x, y):
    return np.sum(np.abs(x - y))
    # جمع الفروق المطلقة

def euclidean_distance(x, y):
    return np.sqrt(np.sum((x - y) ** 2))
    # حساب المسافة الإقليدية

p1 = np.array([1, 2, 3])
p2 = np.array([4, 5, 6])

print(manhattan_distance(p1, p2))
# طباعة Manhattan Distance

print(euclidean_distance(p1, p2))
# طباعة Euclidean Distance

9
5.196152422706632


In [8]:
import numpy as np

table = np.array([[5, 8, 2, 7],
                  [1, 9, 4, 3],
                  [6, 0, 11, 10],
                  [12, 13, 14, 15]])
# إنشاء الجدول

print(table[1])
# الصف الثاني

print(table[:, 2])
# العمود الثالث

print(table[1:3, 1:3])
# جزء من الجدول (صفوف 2-3 وأعمدة 2-3)

[1 9 4 3]
[ 2  4 11 14]
[[ 9  4]
 [ 0 11]]


In [9]:
import numpy as np

scores = np.array([[70, 80, 90],
                   [60, 75, 85],
                   [88, 92, 79],
                   [55, 65, 72]])
# إنشاء مصفوفة الدرجات

scores[:,1] += 5
# زيادة درجات الفيزياء بمقدار 5

scores[0] = [100,100,100]
# تعديل درجات الطالب الأول

scores[:,2] = 0
# جعل عمود CS يساوي صفر

print(scores)

[[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]
